/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  important: true,
  theme: {
    extend: {
      display: ['group-hover'],
      colors: {
        primary: 'var(--primary)',
        primaryThin: 'var(--primaryThin)',
        primaryExtraLight: 'var(--primaryExtraLight)',
        primaryAlt: 'var(--primaryAlt)',
        secondary: 'var(--secondary)',
        accreditationBg: 'var(--acreditationBg)',
        tabHeader: 'var(--tabHeader)',
        icontextColor: 'var(--icontextColor)',
        iconGray: 'var(--icon-gray)',
        mainBgColor: 'var(--mainBgColor)',
        successColor: 'var(--successColor)',
        notificationClr: 'var(--notificationClr)',
        bgWhite: 'var(--bgWhite)',
        bgGrey: 'var(--bgGrey)',
        bgTabHeader: 'var(--bgTabHeader)',
        purpleLight: 'var(--purpleLight)',
        primaryText: 'var(--primaryText)',
        formBorder: 'var(--formBorder)',
        divider: 'var(--divider)',
        hoverColor: 'var(--hoverColor)',
        linkBlue: 'var(--linkBlue)',
        blueLight: 'var(--blueLight)',
        cardWrapperBg: 'var(--cardWrapperBg)',
        bgBadgeColor: 'var(--bgBadgeColor)',
        transparent: 'var(--transparent)',
        white: 'var(--white)',
        black: 'var(--black)',
        danger: 'var(--danger)',
        dangerLight: 'var(--dangerLight)',
        disabledText: 'var(--desabled-text)',
        dangerBorder: 'var(--dangerBorder)',
        blackAlt: 'var(--blackAlt)',
        input: {
          disabled: 'var(--input-disabled)',
        },

        button: {
          primary: 'var(--button-primary)',
          secondary: 'var(--button-secondary)',
        },
        error: {
          'extra-light': 'var(--error-extra-light)',
          light: 'var(--error-light)',
          dark: 'var(--error-dark)',
          DEFAULT: 'var(--error)',
        },
        success: {
          light: 'var(--success-light)',
          DEFAULT: 'var(--success)',
        },
        grey: {
          dark: 'var(--grey-dark)',
          strong: 'var(--grey-strong)',
          medium: 'var(--grey-medium)',
          mediumAlt: 'var(--grey-mediumAlt)',
          light: 'var(--grey-light)',
          lightHover: 'var(--grey-lightHover)',
          lightAlt: 'var(--grey-lightAlt)',
          border: 'var(--grey-border)',
          borderAlt: 'var(--grey-borderAlt)',
        },
        // tabHeader: '#F1F3FF',
        // icontextColor: '#ffffff',
        // mainBgColor: '#fafafa',
        // successColor: '#1ACDA5',
        // dangerColor: '#E76458',
        // notificationClr: '#E76458',
        // bgWhite: '#ffffff',
        // bgGrey: '#F2F2F2',
        // bgTabHeader: '#F3F3F3',
        // purpleLight: '#FCF7FD',
        // primaryText: '#606060',
        // formBorder: '#E6E8EA',
        // divider: '#D6D8DC',
        // hoverColor: '#FDF0EF',
        // linkBlue: '#336CFC',
        // cardWrapperBg: '#F8F8F8',
        // bgBadgeColor: '#C90909',
        // transparent: 'transparent',
        // white: '#ffffff',
        // black: '#000000',
        // danger: '#E25A5A',
        // dangerLight: '#FFF8F8',
        // dangerBorder: '#E764581A',
        // blackAlt: '#222222',
        // backgroundImage: {
        //   primaryGradient: 'linear-gradient(#4757E0, #5B58E6D4)',
        // },
        // input: {
        //   disabled: '#D7D6D6',
        // },
        // button: {
        //   primary: 'var(--primary) !important',
        //   secondary: '#6B6F82 !important',
        // },

        // error: {
        //   'extra-light': '#f9dada',
        //   light: '#E55353',
        //   dark: '#FF000F',
        //   DEFAULT: '#C63A3A',
        // },
        // success: {
        //   light: '#E2F8E3',
        //   DEFAULT: '#299957',
        // },
        // grey: {
        //   dark: '#85888E',
        //   strong: '#313131',
        //   medium: '#585858',
        //   mediumAlt: '#999696',
        //   light: '#D6D8DC99',
        //   lightHover: '#f8f8f8',
        //   lightAlt: '#F4F4F4',
        //   border: '#D6D8DC',
        //   borderAlt: '#c6c6c6',
        // },
      },
      borderRadius: {
        none: '0',
        DEFAULT: '10px',
        button: '10px',
        input: '3px',
        md: '8px',
        sm: '6px',
        xs: '4px',
      },

      fontSize: {
        xxxl: '24px',
        xxl: '21px',
        xl: '20px',
        l: '18px',
        m: '16px',
        s: '15px',
        common: '14px',
        xs: '13px',
        xxs: '12px',
      },
      boxShadow: {
        card: '0 5px 28px #5F5A5A12',
      },
      padding: {
        headetabPx: '10px',
        headetabPy: '18px',
      },
    },
  },

  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
  ],
}
