/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  important: true,
  theme: {
    extend: {
      display: ['group-hover'],
      colors: {
   primaryBlue:'#1072D7',
   primaryPink:'#FF2E99',
   primaryGreen:'#0fc8cd',
        primaryThin: '#C7D2FE',
        primaryExtraLight: '#D1D9FF',
        primaryAlt: '#4F46E5',
        accreditationBg: '#F7F7F7',
        tabHeader: '#F1F3FF',
        icontextColor: '#ffffff',
        iconGray: '#C5C5C5',
        mainBgColor: '#fafafa',
        successColor: '#1ACDA5',
        notificationClr: '#E76458',
        bgWhite: '#ffffff',
        bgGrey: '#F2F2F2',
        bgTabHeader: '#F3F3F3',
        purpleLight: '#FCF7FD',
        primaryText: '#606060',
        formBorder: '#E6E8EA',
        divider: '#D6D8DC',
        hoverColor: '#FDF0EF',
        linkBlue: '#336CFC',
        blueLight: '#ADD8E6',
        cardWrapperBg: '#F8F8F8',
        bgBadgeColor: '#C90909',
        transparent: 'transparent',
        white: '#ffffff',
        black: '#000000',
        danger: '#E25A5A',
        dangerLight: '#FFF8F8',
        disabledText: '#D7D6D6',
        dangerBorder: '#E764581A',
        blackAlt: '#222222',
        input: {
          disabled: '#D7D6D6',
        },
        button: {
          primary: '#3B82F6',
          secondary: '#6B6F82',
        },
        error: {
          'extra-light': '#f9dada',
          light: '#E55353',
          dark: '#FF000F',
          DEFAULT: '#C63A3A',
        },
        success: {
          light: '#E2F8E3',
          DEFAULT: '#299957',
        },
        grey: {
          dark: '#85888E',
          strong: '#313131',
          medium: '#585858',
          mediumAlt: '#999696',
          light: '#D6D8DC99',
          lightHover: '#f8f8f8',
          lightAlt: '#F4F4F4',
          border: '#D6D8DC',
          borderAlt: '#c6c6c6',
        },

      },
      borderRadius: {
        none: '0',
        DEFAULT: '10px',
        button: '10px',
        input: '3px',
        md: '8px',
        sm: '6px',
        xs: '4px',
      },

      fontSize: {
        xxxl: '24px',
        xxl: '21px',
        xl: '20px',
        l: '18px',
        m: '16px',
        s: '15px',
        common: '14px',
        xs: '13px',
        xxs: '12px',
      },
      boxShadow: {
        card: '0 5px 28px #5F5A5A12',
      },
      padding: {
        headetabPx: '10px',
        headetabPy: '18px',
      },
    },
  },

  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
  ],
}
