import { useState } from 'react'
import { QbsTable } from 'qbs-react-grid'
import { calcWindowHeight } from '../../../utilities/calcHeight'
import { createClientReport, useClientReports } from '../api'
import Button from '../../../components/common/buttons/Button'
import { useSnackbarManager } from '../../../components/common/snackbar'
import { AutoComplete } from 'qbs-core'

export default function Reports({ user }: { user: any }) {
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [month, setMonth] = useState<number | ''>('')
  const [year, setYear] = useState<number | ''>('')
  const [generating, setGenerating] = useState(false)
  const { enqueueSnackbar } = useSnackbarManager()

  const { data, isFetching, refetch } = useClientReports({
    user_id: user?.id,
    page,
    per_page: pageSize,
  } as any)

  const items = data?.items || []

  const months = [
    { id: '1', name: 'JANUARY' },
    { id: '2', name: 'FEBRUARY' },
    { id: '3', name: 'MARCH' },
    { id: '4', name: 'APRIL' },
    { id: '5', name: 'MAY' },
    { id: '6', name: 'JUNE' },
    { id: '7', name: 'JULY' },
    { id: '8', name: 'AUGUST' },
    { id: '9', name: 'SEPTEMBER' },
    { id: '10', name: 'OCTOBER' },
    { id: '11', name: 'NOVEMBER' },
    { id: '12', name: 'DECEMBER' },
  ]

  const years = Array.from({ length: 6 }, (_, i) => {
    const y = 2025 - i
    return { id: String(y), name: String(y) }
  })

  const columns: any[] = [
    {
      title: 'User',
      field: 'user_name',
      customCell: true,
      renderCell: (row: any) => ({
        cell: row?.user_name,
        toolTip: row?.user_name,
      }),
      sortable: false,
      resizable: true,
      isVisible: true,
    },
    {
      title: 'Month',
      field: 'month',
      customCell: true,
      renderCell: (row: any) => ({
        cell: String(row?.month ?? ''),
        toolTip: String(row?.month ?? ''),
      }),
      sortable: false,
      resizable: true,
      isVisible: true,
    },
    {
      title: 'Year',
      field: 'year',
      customCell: true,
      renderCell: (row: any) => ({
        cell: String(row?.year ?? ''),
        toolTip: String(row?.year ?? ''),
      }),
      sortable: false,
      resizable: true,
      isVisible: true,
    },
    {
      title: 'Total Workouts',
      field: 'total_workouts_done',
      customCell: true,
      renderCell: (row: any) => ({
        cell: String(row?.total_workouts_done ?? 0),
        toolTip: String(row?.total_workouts_done ?? 0),
      }),
      sortable: false,
      resizable: true,
      isVisible: true,
    },
    {
      title: 'Avg BMI',
      field: 'avg_bmi',
      customCell: true,
      renderCell: (row: any) => ({
        cell: String(row?.avg_bmi ?? ''),
        toolTip: String(row?.avg_bmi ?? ''),
      }),
      sortable: false,
      resizable: true,
      isVisible: true,
    },
    {
      title: 'Generated By',
      field: 'generated_by',
      customCell: true,
      renderCell: (row: any) => ({
        cell: row?.generated_by || '',
        toolTip: row?.generated_by || '',
      }),
      sortable: false,
      resizable: true,
      isVisible: true,
    },
  ]

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-end justify-between">
        <div className="flex gap-3">
          <div className="min-w-[220px]">
            <label className="block text-sm text-gray-600 mb-1">Month</label>
            <AutoComplete
              name="report_month"
              type="custom_select"
              desc="name"
              descId="id"
              data={months}
              placeholder={'Month'}
              value={
                (months.find((m) => Number(m.id) === month)?.name as string) ??
                ''
              }
              onChange={(opt: any) => setMonth(opt?.id ? Number(opt.id) : '')}
            />
          </div>
          <div className="min-w-[220px]">
            <label className="block text-sm text-gray-600 mb-1">Year</label>
            <AutoComplete
              name="report_year"
              type="custom_select"
              desc="name"
              descId="id"
              data={years}
              placeholder={'Year'}
              value={
                (years.find((y) => Number(y.id) === year)?.name as string) ?? ''
              }
              onChange={(opt: any) => setYear(opt?.id ? Number(opt.id) : '')}
            />
          </div>
        </div>
        <Button
          className="bg-primaryGreen"
          label={generating ? 'Generating...' : 'Generate Report'}
          onClick={async () => {
            if (!user?.id || !month || !year) return
            try {
              setGenerating(true)
              await createClientReport({ user_id: user.id, month, year })
              enqueueSnackbar('Report generated successfully', {
                variant: 'success',
              })
              await refetch()
              setMonth('')
              setYear('')
            } catch (e: any) {
              enqueueSnackbar(
                e?.response?.data?.message || 'Failed to generate report',
                { variant: 'error' }
              )
            } finally {
              setGenerating(false)
            }
          }}
          disabled={generating || !user?.id || !month || !year}
        />
      </div>

      <QbsTable
        data={items}
        dataRowKey="id"
        toolbar={false}
        search={false}
        isLoading={isFetching}
        height={
          items?.length === 0 ? calcWindowHeight(218) : calcWindowHeight(300)
        }
        emptyTitle="No reports to display"
        emptySubTitle={''}
        columns={columns}
        pagination={true}
        paginationProps={{
          onPagination: (p: number) => setPage(p),
          total: data?.total ?? 0,
          currentPage: data?.current_page ?? page,
          rowsPerPage: Number(pageSize),
          onRowsPerPage: (n: number | string) => setPageSize(Number(n)),
          dropOptions: [10, 20, 30, 50, 100],
        }}
      />
    </div>
  )
}
